# Generated by Django 4.2 on 2023-04-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('object_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('object_label', models.CharField(blank=True, max_length=1000)),
                ('object_name', models.CharField(blank=True, max_length=1000)),
                ('fields', models.CharField(blank=True, max_length=1000)),
                ('row_count_org_one', models.IntegerField(blank=True, null=True)),
                ('row_count_org_two', models.IntegerField(blank=True, null=True)),
                ('matching_rows_count_org_one', models.IntegerField(blank=True, null=True)),
                ('matching_rows_count_org_two', models.IntegerField(blank=True, null=True)),
                ('unmatching_rows_count_org_one', models.IntegerField(blank=True, null=True)),
                ('unmatching_rows_count_org_two', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('api_name', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparedata.job')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_number', models.PositiveSmallIntegerField()),
                ('access_token', models.CharField(max_length=255)),
                ('instance_url', models.CharField(max_length=255)),
                ('org_id', models.CharField(max_length=255)),
                ('org_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comparedata.job')),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparedata.job')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparedata.org')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('api_name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparedata.object')),
            ],
        ),
    ]
